const dummyProducts = [
    {
      id: '1',
      name: 'Wireless Headphones',
      image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
      price: 299.99,
      category: 'Electronics',
      description: 'High-quality wireless headphones with noise-canceling features.',
    },
    {
      id: '2',
      name: 'Smartwatch Pro',
      image: 'https://images.pexels.com/photos/277394/pexels-photo-277394.jpeg',
      price: 149.99,
      category: 'Wearables',
      description: 'Stylish smartwatch with fitness tracking and heart-rate monitoring.',
    },
    {
      id: '3',
      name: 'Gaming Mouse',
      image: 'https://images.pexels.com/photos/4792730/pexels-photo-4792730.jpeg',
      price: 59.99,
      category: 'Accessories',
      description: 'Ergonomic mouse with customizable RGB lighting and precision sensor.',
    },
    {
      id: '4',
      name: 'Bluetooth Speaker',
      image: 'https://images.pexels.com/photos/63703/pexels-photo-63703.jpeg',
      price: 89.99,
      category: 'Audio',
      description: 'Portable Bluetooth speaker with deep bass and 12-hour battery life.',
    },
    {
      id: '5',
      name: 'Mechanical Keyboard',
      image: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg',
      price: 129.99,
      category: 'Computers',
      description: 'Tactile mechanical keyboard with customizable keys and RGB lighting.',
    },
    {
      id: '6',
      name: 'Digital Camera',
      image: 'https://images.pexels.com/photos/994605/pexels-photo-994605.jpeg',
      price: 599.99,
      category: 'Photography',
      description: 'Compact digital camera with 20MP resolution and optical zoom.',
    },
    {
      id: '7',
      name: 'Fitness Tracker',
      image: 'https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg',
      price: 49.99,
      category: 'Fitness',
      description: 'Lightweight fitness band for tracking steps, calories, and sleep.',
    },
    {
      id: '8',
      name: 'Noise-Canceling Earbuds',
      image: 'https://images.pexels.com/photos/373945/pexels-photo-373945.jpeg',
      price: 119.99,
      category: 'Audio',
      description: 'Compact earbuds with superior sound and active noise cancelation.',
    },
    {
      id: '9',
      name: '4K Monitor',
      image: 'https://images.pexels.com/photos/572056/pexels-photo-572056.jpeg',
      price: 399.99,
      category: 'Monitors',
      description: 'Ultra HD 4K display with wide color gamut and minimal bezels.',
    },
    {
      id: '10',
      name: 'Portable Charger',
      image: 'https://images.pexels.com/photos/1194713/pexels-photo-1194713.jpeg',
      price: 29.99,
      category: 'Power',
      description: 'Compact power bank with fast-charging and 10,000mAh capacity.',
    },
    {
      id: '11',
      name: 'VR Headset',
      image: 'https://images.pexels.com/photos/4009626/pexels-photo-4009626.jpeg',
      price: 249.99,
      category: 'Gaming',
      description: 'Immersive virtual reality headset with built-in spatial audio.',
    },
    {
      id: '12',
      name: 'Laptop Stand',
      image: 'https://images.pexels.com/photos/4778403/pexels-photo-4778403.jpeg',
      price: 39.99,
      category: 'Accessories',
      description: 'Adjustable aluminum stand for better laptop ergonomics.',
    },
  ];
  
  export default dummyProducts;
  